### PR TITLE
Added on:blur event, and disable option

### PR DESCRIPTION
**Pull request by agustinl**
* Added the `on:blur` event #21 
* Removed duplicate <kbd>ENTER</kbd> and <kbd>BACKSPACE</kbd> check
* Added `disable` option #23

### CODE REVIEW

**Comment by agustinl** [comment]
+ @alperenozlu

**Comment by alperenozlu** [comment]
@agustinl Do you have any plan to add customizable on:blur and on:focus functions?

**Comment by agustinl** [comment]
@alperenozlu for example? 🤔 I added to `sti-staged` branch the on:blur event., to allow add a tag.

**Comment by alperenozlu** [comment]
@agustinl passing custom function to on:blur, for example when blur, submit my form. Current development is only support for add tag on blur.

`<Tag  ..... on:blur={(lastTag)=>{  tags = [...tags, lastTag]; submitMyForm();     });
`

In this version, user's need to define an event listener for doing that.

**Comment by agustinl** [comment]
@alperenozlu 
mm not for now, I didn't think to include any method for now.
But it is something that we can work on and include several at once in the future.
Like a big release 🚀

**Pull request merged**
